### ISSUE TITLE
Can't get attribute 'DetectionModel' on <module 'models.yolo' from....>

### ISSUE THREAD

**Issue by LeolineZ** [pooya-mohammadi/yolov5-gradcam#23]
Here's my code...↓
```python

! pip install -r requirements.txt

import os
os.chdir("./yolov5-gradcam-master/")

!python main.py --model-path runs/train/hat_person4/weights/best.pt --img-path datasets/hat_person/yolo_dataset/images/train/000490.jpg --output-dir outputs --names hat,person   

```

And then...Something wrong..

> **[INFO] Loading the model**
**Traceback (most recent call last):**
    File "main.py", line 124, in <module>
    main(args.img_path)
  File "main.py", line 64, in main
    names=None if args.names is None else args.names.strip().split(","))
  File "f:\works\VSCODE\yolov5\yolov5-gradcam-master\models\yolo_v5_object_detector.py", line 32, in `__init__`
    self.model = attempt_load(model_weight, device=device)
  File "f:\works\VSCODE\yolov5\yolov5-gradcam-master\models\experimental.py", line 80, in attempt_load
    ckpt = torch.load(attempt_download(w), map_location=device)
  File "d:\Anaconda3\envs\yolo\lib\site-packages\torch\serialization.py", line 607, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "d:\Anaconda3\envs\yolo\lib\site-packages\torch\serialization.py", line 882, in _load
    result = unpickler.load()
  File "d:\Anaconda3\envs\yolo\lib\site-packages\torch\serialization.py", line 875, in find_class
    return super().find_class(mod_name, name)
AttributeError: Can't get attribute 'DetectionModel' on <module 'models.yolo' from 'f:\\works\\VSCODE\\yolov5\\yolov5-gradcam-master\\models\\yolo.py'>

**Comment by present-gift** [comment]
do you fix it?

**Comment by LeolineZ** [comment]
> do you fix it?

not yet

**Comment by saisriteja** [comment]
did you fix it?

**Comment by mcasini** [comment]
same problem

**Comment by mohaliyet** [comment]
anyone fixed the issue?

**Comment by LinRds** [comment]
I fix it by update the models/yolo.py  (yolov5 reposipotry)

**Comment by mohaliyet** [comment]
@LinRds could you please tell me how? Or, direct me to the updated fork?

**Comment by xiaoling-1** [comment]
> I fix it by update the models/yolo.py (yolov5 reposipotry)



Which version of yolov5?

**Comment by LinRds** [comment]
> 
v7.0

**Comment by LinRds** [comment]
> @LinRds could you please tell me how? Or, direct me to the updated fork?

v 7.0

**Comment by LinRds** [comment]
> 

v 7.0

**Comment by kiran-coditation** [comment]
Hey does anyone know the solution of this issue ?  @LinRds @saisriteja @mohaliyet @xiaoling-1

**Comment by iurimolina** [comment]
same problem here

**Comment by iurimolina** [comment]
did anyone fix this?

**Comment by rokopi-byte** [comment]
The problem is retated to the yolov5 version used to train the model vs the version included in this repo. A quick fix is to add in yolo.py at line 251 the following:

DetectionModel = Model
